### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by lukepaulkopera** [LawnchairLauncher/lawnicons#102]
Textra - 
com.textra

Samsung Internet Beta - com.sec.android.app.sbrowser.beta

YT Vanced Music - 
com.vanced. android.apps.youtube.music

Jak dojadę - 
com.citynav.jakdojade.pl. android

Peopay - 
softax.pekao.powerpay

Google Pay - 
com.google.android.apps.walletnfcrel

**Comment by Ishaanrathod09** [comment]
Request for twitter lite and blackhole music player themed icons

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
