### ISSUE TITLE
[DISCUSSION] Hidden apps: Search should not show

### ISSUE THREAD

**Issue by Pantyhose-X** [LawnchairLauncher/lawnicons#1022]
### About this discussion

Lend your phone to a friend or your kid at home, and you install some NSFW software 😰 so the hidden apps shouldn't be searched for,
The list of hidden apps should be shown with a PIN, or the whole list of apps should have a PIN, PIN is not correct, only home apps can be viewed

**Comment by vickensemerdjian** [comment]
Imo just don't install that, the hidden apps is mostly for clutter

**Comment by thismoon** [comment]
I think this issue is related to the launcher itself ([LawnchairLauncher/lawnchair](https://github.com/LawnchairLauncher/lawnchair)) rather than lawnicons

and a commit ([#3032](https://github.com/LawnchairLauncher/lawnchair/pull/3032)) made it so you can only see them when their full name is typed, so you can compile the launcher yourself or wait for a new update if you want that feature

**Comment by Pantyhose-X** [comment]
Question moves to https://github.com/LawnchairLauncher/lawnchair/issues/3402
