### ISSUE TITLE
Add Yandex icon

### ISSUE THREAD

**Issue by incycledream** [LawnchairLauncher/lawnicons#103]
app name: Yandex
pkg name: ru.yandex.searchplugin

**Comment by 00p513-dev** [comment]
Which style would you prefer? The Y icon or the Russian Я icon?

**Comment by itunity6661** [comment]
russian Я icon

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
