### ISSUE TITLE
Disney+, HBO Max, web video cast, crunchyroll, tv time, Camera, Chrome remote Desktop, Google Pay, Google opinion rewards app icons please

### ISSUE THREAD

**Issue by Orphen1989** [LawnchairLauncher/lawnicons#115]
Disney +: com.disney.disneyplus
HBO Max: com.hbo.hbonow
Web video cast: com.instantbits.cast.webvideo
Crunchyroll: com.crunchyroll.crunchyroid
TV time: com.tozelabs.tvshowtime
Camera: com.android.MGC
Chrome remote Desktop: com.google.chromeremotedesktop
Google Pay: com.google.android.apps.walletnfcrel
Google opinion rewards: com.google.android.apps.paidtasks

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
