### ISSUE TITLE
Please also link dialer icon to 

### ISSUE THREAD

**Issue by Yurieaijoker** [LawnchairLauncher/lawnicons#117]
Please also link 

dialer icon to "com.android.phone" & "com.android.contacts.activities.DialtactsActivity"

Contact icon to "com.android.contacts" 

thank you.

**Comment by Yurieaijoker** [comment]
Hi, the huawei phone app is still not working tho its link i don't know what is wrong.

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
