### ISSUE TITLE
Please map Samsung browser icon to samsung browser beta

### ISSUE THREAD

**Issue by meistr91** [LawnchairLauncher/lawnicons#142]
Hi guys, can you please link/map samsung browser icon to samsung browser beta?

Package name:
com.sec.android.app.sbrowser.beta

I would really appreciate that!

**Comment by arun54321** [comment]
Now Samsung internet beta has its own icon. I think you may close this issue.

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
