### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Application-maker** [LawnchairLauncher/lawnicons#1453]
### About this discussion

There are some duplicates in Lawnicons, I've used the [IconRequest app](https://github.com/Kaiserdragon2/IconRequest) to make [this list of duplicates](https://privatebin.io/?f0e69303502ccfcb#8JVoR5B772yUKPbVu9TK1KfVDbG9NsghWnyf8i4MtNdc).

**Comment by x9136** [comment]
Duplicates gradually accumulate because many people add components manually, and keeping track of thousands of lines in appfilter.xml is difficult.

So if you want, you can [find duplicates with a script](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/icontool_guide.md#finding-duplicate-entries-in-appfilterxml), remove them and create a PR, but after time new duplicates will appear.

**Comment by KTibow** [comment]
> However, periodically the developers remove duplicates.

It's up to you if you do this but I'd like to see an example commit

**Comment by x9136** [comment]
> I'd like to see an example commit

https://github.com/LawnchairLauncher/lawnicons/pull/1090/commits/5b1cef5cadd1dbfeabe0ed9c7154fd926acb5c50
https://github.com/LawnchairLauncher/lawnicons/commit/92c002cd731f059d4c6ccf5f189aa5ef048d5909
