### ISSUE TITLE
Imo messenger

### ISSUE THREAD

**Issue by kangurtboy** [LawnchairLauncher/lawnicons#149]
Please add themed icon on 
[Imo messenger](https://play.google.com/store/apps/details?id=com.imo.android.imoim)
And imo lite version
[Imo lite](https://play.google.com/store/apps/details?id=com.imo.android.imoimlite)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
