### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Suraj-Shiva** [LawnchairLauncher/lawnicons#160]
app:AmoledPix
package:com.androholic.amoledpix

app:Weather
package:com.vivo.weather

app:Compass
package:com.vivo.compass

app:STOKiE PRO
package:com.harry.stokiepro

app:Pocket
package:com.ideashower.readitlater.pro

app:Swiggy
package:in.swiggy.android

app:Doodle
package:xyz.zedler.patrick.doodle

app:Fantasia Painter
package:com.datcompany.fantasiapainter

app:Pastel Wallpapers
package:com.arrow.wallpapers.pastelwall

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
