### ISSUE TITLE
[DISCUSSION] Linux port?

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [LawnchairLauncher/lawnicons#1678]
### About this discussion

Would it be possible for some sort of Linux port?
Maybe using some sort of simple script that samples colors from the wallpaper and then installs a colored version of the icons?

**Comment by KTibow** [comment]
This wouldn't make sense because you don't run Android apps on linux

**Comment by SuperDragonXD** [comment]
It is possible (just do some fiddling around with the svgs + bash), but unfortunately our developers mostly specialize in Android development, not Linux development. Porting Lawnicons would just be difficult to do since after all, it's an Android app. Therefore, we will *not* port Lawnicons to other platforms. Feel free to make a PR if you can to implement this feature.
