### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by kostasntamas** [LawnchairLauncher/lawnicons#172]
• Revolut (Package com.revolut.revolut)
• Gpay (Package com.google.android.apps.walletnfcrel)
• Wnbank (Package gr.winbank.mobilenext)
• Oneplus Community (Package net.oneplus.forums)
• Oneplus Health app
(Packagecom.oneplus.health.international)
• Adaway (org.adaway)
• Tasker ( Package net.dinglisch.android.taskerm) 
• Flud (com.delphicoder.flud) 
• Paypal (Package com.paypal.android.p2pmobile)

Thanks for your work

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
