### ISSUE TITLE
Consider removing Temu and Shein

### ISSUE THREAD

**Issue by ThatOneCalculator** [LawnchairLauncher/lawnicons#1733]
### About this discussion

Temu is a (suspected) spyware application currently under investigation from the US government, and their sister app has been banned off of Google Play and the Apple App Store for containing malicious code. Shein is based on the same base as Temu and their businesses have ties. Lawnicons should not be supporting such apps or businesses.

**Comment by x9136** [comment]
It's just a set of icons.

If you evaluate each app to see if it complies with the laws of one country or another, there will be plenty of apps that don't comply with US laws (for example), but do comply with the laws of other countries. Revanced, Sberbank, Tinkoff, etc.

Apps that are harmful suck. People are capable of deciding for themselves what to install on their phone. In my opinion, the most important thing is that the user feels comfortable using a set of icons. Lawnicons are used all over the world. If you make a set of icons that will be cleared of apps that are suspicious in any way or violate any law of any country, then such a set will not be comfortable for anyone.

If there is a virus embedded in the app and there is proof, only then in my opinion you should consider deleting it. However, your options are quietly available on Google Play right now.

**Comment by ThatOneCalculator** [comment]
Temu has spyware. 

https://www.thecorporatelawjournal.com/technology/chinese-marketplace-temu-faces-class-action-lawsuit-for-spyware-and-malicious-business-practices
https://www.classaction.org/news/data-breach-class-action-claims-temus-in-app-web-browser-secretly-tracks-users
https://www.usatoday.com/story/tech/columnist/komando/2023/04/20/delete-temu-app-cybersecurity-expert-advice/11667796002/https://www.fashiondive.com/news/temu-class-action-lawsuit-data-collection/699328/

**Comment by ThatOneCalculator** [comment]
The fact that it's even owned by a company that has put out virus and spyware ridden apps should be a huge immediate red flag.

**Comment by ThatOneCalculator** [comment]
Also, "it's just a set of icons" isn't a great argument. By putting an app in an icon pack, it holds some meaning like "oh, people use this app since this big project has an icon for it. I should be fine using it too"

**Comment by x9136** [comment]
> Temu has spyware.

It's a reason to evaluate your trust in an app. If you don't trust the app, you don't install it.

> Also, "it's just a set of icons" isn't a great argument. By putting an app in an icon pack, it holds some meaning like "oh, people use this app since this big project has an icon for it. I should be fine using it too"

The presence of an icon in any set has no bearing on the decision to install an app. The reason is that a person makes a decision to install the app based on its usefulness, rather than going to check whether there is an icon in the set before installing the app. Also, the presence of an icon doesn't affect whether a person uninstalls the app or not. People who like the app without an icon will either install some suitable icon on it or request an icon for that app.

There are also plenty of people who don't care what data is collected about them. They will make good use of any app. If you want dry stats, making a Temu icon was asked 2 times, as was Shein. At the moment, it's 4 vs 1.

I've said enough. I wouldn't remove any icon if at least a meaningful number of people are using the app, as it has no effect on installing or uninstalling apps. Especially when it comes to apps that are available on Google Play. It's not just up to me, though.

If someone wants to join the discussion, they will do so. Thank you for being concerned about it.

**Comment by KTibow** [comment]
Arguably if it was removed it would just lead to requests, issues, and PRs
