### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Codecracker508** [LawnchairLauncher/lawnicons#174]
app:Airtel
package:com.myairtelapp

app:AmoledPix
package:com.androholic.amoledpix

app:Calculator
package:com.google.android.calculator

app:Brainly
package:co.brainly

app:CareerLabs Elev8
package:com.careerlabs

app:Carrom King
package:com.git.carromking

app:Feedback
package:com.vivo.feedback

app:iManager
package:com.vivo.imanager

app:InShare
package:sharefiles.sharemusic.shareapps.filetransfer

app:iqoo.com
package:com.iqoo.website

app:Koloro
package:com.cerdillac.persetforlightroom

app:Myntra
package:com.myntra.android

app:Notes
package:com.vivo.notes

app:Package Names
package:com.csdroid.pkg

app:PixelLab
package:com.imaginstudio.imagetools.pixellab

app:PLAYit
package:com.playit.videoplayer

app:PUBG MOBILE
package:com.pubg.krmobile

app:PUBG: NEW STATE
package:com.pubg.newstate

app:Recorder
package:com.vivo.soundrecorder

app:Smartprix
package:com.smartprix.main

app:SoloVPN
package:co.solovpn

app:SpotaFree
package:com.release.spotafree

app:TapTap
package:com.taptap.global

app:UFO VPN
package:com.fast.ufovpn.proxy

app:Vanced Manager
package:com.vanced.manager

app:Zapya
package:com.dewmobile.kuaiya.play

**Comment by arun54321** [comment]
google calculator app already works.

**Comment by kazooduck** [comment]
Vouch for spotifree

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
