### ISSUE TITLE
Icon request: Microsoft One Note

### ISSUE THREAD

**Issue by Yurieaijoker** [LawnchairLauncher/lawnicons#196]
Please add icon lawnicons for Microsoft OneNote. Thank you. 
Package: (com.microsoft.office.onenote)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
