### ISSUE TITLE
Icon Request: Obsidian, Libby, Mullvad, AntennaPod, Loop Habit Tracker

### ISSUE THREAD

**Issue by qsyntrax** [LawnchairLauncher/lawnicons#221]
Obsidian: md.obsidian
Libby: com.overdrive.mobile.android.libby
Mullvad: net.mullvad.mullvadvpn
AntennaPod: de.danoeh.antennapod
Loop Habit Tracker: org.isoron.uhabits

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
