### ISSUE TITLE
Add icon for Mobile Legends: Bang Bang

### ISSUE THREAD

**Issue by dmsfzn** [LawnchairLauncher/lawnicons#240]
Package name: com.mobile.legends
Love your project

**Comment by dirasmaulana** [comment]
Mantap

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
