### ISSUE TITLE
Icon Request (Pillars,Pulse, Lightroom,Google pay)

### ISSUE THREAD

**Issue by Shayaan-Azeem** [LawnchairLauncher/lawnicons#242]
Pillars: com.pillars.pillars 

Brightspace Pulse: com.d2l.brightspace.student.android

Adobe Lightroom: com.adobe.lrmobile

Google Pay: com.google.android.apps.walletnfcrel

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
