### ISSUE TITLE
Icon Request: Notally

### ISSUE THREAD

**Issue by TeaspoonOnTheTable** [LawnchairLauncher/lawnicons#260]
![NotallyIcon](https://user-images.githubusercontent.com/97811600/174555176-cf7e42e2-bf28-46ee-a2ba-11193b881926.png)

Notally

`com.omgodse.notally`

Thanks :)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
