### ISSUE TITLE
Emui system icons and Others

### ISSUE THREAD

**Issue by JustLukz** [LawnchairLauncher/lawnicons#27]
Emui system icons, Opera GX, eBay Kleinanzeigen and Apple Music

**Comment by ninopiamonte** [comment]
#58

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
