### ISSUE TITLE
Icon Request : 365 Scores App

### ISSUE THREAD

**Issue by matiasmaxi** [LawnchairLauncher/lawnicons#271]
com.scores365 (play store)
![365 Scores](https://user-images.githubusercontent.com/98232179/150651150-14065321-49d9-485a-8074-318634134cd6.jpg)

Thanks

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
