### ISSUE TITLE
Icon Request: Creative App, WAIFUPX

### ISSUE THREAD

**Issue by dg-encrypt** [LawnchairLauncher/lawnicons#273]
Creative App
com.kubix.creative
![Screenshot_2022-01-22-13-01-48-124_com miui securitycenter~01](https://user-images.githubusercontent.com/84547231/150651986-f0997437-9c24-46bc-8a40-79da6aef434b.jpg)

WAIFUPX
dg.waifu.walls
![PicsArt_01-22-12 47 30~01](https://user-images.githubusercontent.com/84547231/150651992-5942fe55-6302-4c57-9626-7f14b9973b26.png)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
