### ISSUE TITLE
Icon Request: Material Files, Tasker

### ISSUE THREAD

**Issue by rufus582** [LawnchairLauncher/lawnicons#287]
Material Files: me.zhanghai.android.files
Tasker: net.dinglisch.android.taskerm
I had already requested the icon for tasker a long time ago, but I'm not sure why it's being added🤔. Would like to have these app icons themed😊

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
