### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/lawnicons#291]
File Manager+
com.alphainventor.filemanager
Google Camera
com.samsung.android.scan3d
 Kate Mobile
com.perm.kate
 Vk Mp3 Mod
com.vkmp3mod.android
Anixart
com.swiftsoft.anixartd
Fenix
it.mvilla.android.fenix2
Murglar2
com.badmanners.murglar2
RetroMusic
code.name.monkey.retromusic
4PDA
ru.fourpda.client

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
