### ISSUE TITLE
OctaviDialer 3.3 Icon Not Themed

### ISSUE THREAD

**Issue by shoshi007** [LawnchairLauncher/lawnicons#300]
OctaviDialer 3.3
package name : com.android.dialer.apk

**Comment by sweetcock69** [comment]
bump

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
