### ISSUE TITLE
Icon request: Some apps that don't have a custom icon

### ISSUE THREAD

**Issue by zzinkoo** [LawnchairLauncher/lawnicons#305]
app:Crunchyroll
package:com.crunchyroll.crunchyroid

app:E-mail
package:com.samsung.android.email.provider

app:Genshin Impact
package:com.miHoYo.GI.samsung

App:Globoplay
package:com.globo.globotv

app:Google Play Games
package:com.google.android.play.games

app:ibisPaint X
package:jp.ne.ibis.ibispaintx.app

app:PicPay
package:com.picpay

app:Canva
package:com.canva.editor

app:Calendar
package:com.samsung.android.calendar

app:Game Launcher
package:com.samsung.android.game.gamehome

app:osu!
package:sh.ppy.osulazer

app:RL Sideswipe
package:com.Psyonix.RL2D

app:Relógio (Clock)
package:com.sec.android.app.clockpackage

app:Galaxy Store
package:com.sec.android.app.samsungapps

app:Clima (Weather)
package:com.sec.android.daemonapp

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
