### ISSUE TITLE
Request for icon theming 

### ISSUE THREAD

**Issue by Vysakhkj** [LawnchairLauncher/lawnicons#307]
1. Samsung calendar
com.samsung.android.calendar
2. Samsung camera
com.sec.android.app.camera
3. Samsung clock
com.sec.android.app.clockpackage
4. Samsung contacts
com.samsung.android.app.contacts
5. English Malayalam Dictionary
Syamu.Dictionary.Sarada
6. Samsung Gallery
com.sec.android.gallery3d
7. KDE connect
org.kde.kdeconnect_tp
8. Manglish Keyboard
com.clusterdev.malayalamkeyboard
9. Samsung Radio
com.sec.android.app.fm
10. Samsung pay mini
com.samsung.android.spaymini
11. Samsung music
com.sec.android.app.music
12. Samsung voice recorder
com.sec.android.app.voicenote
13. Samsung calculator
com.sec.android.app.popupcalculator
14. Google opinion Rewards
com.google.android.apps.paidtasks
15. Sticker maker
com.marsvard.stickermakerforwhatsapp
16. Aimp
com.aimp.player
17. Stokie
com.harry.stokie
18. Galaxy Store
com.sec.android.app.samsungapps
19. Galaxy themes
com.samsung.android.themestore
20. Vflat
com.voyagerx.scanner
21. Pi video player
com.project100pi.videoplayer.video.player
22. Olam dictionary
com.olam
23. Resso
com.moonvideo.android.resso

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
