### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by watham15** [LawnchairLauncher/lawnicons#313]
Notion - notion.id
today weather - mobi.lockdown.weather
tachij2k - eu.kanade.tachiyomi.j2k
openweather - uk.co.openweather
tick-tick - com.ticktick.task
taskito - com.fenchtose.reflog
kuro - com.deceptions.no
neko - tachiyomi.mangadex
pulse music - com.hardcodecoder.pulse

**Comment by halacoglu** [comment]
TickTick is waiting to be merged :) #275

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
