### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by AhmedYasser22710** [LawnchairLauncher/lawnicons#319]
Please do themed icon for that gcam
![Screenshot_20220202-154823_Lawnchair_1](https://user-images.githubusercontent.com/65810567/152167905-b5de48b0-c800-4a07-94ff-1e83bec32cc3.png)
![Screenshot_20220202-154951_Settings_1](https://user-images.githubusercontent.com/65810567/152168002-b23a78dd-c6ac-4046-bbd7-ab89448e566f.png)
As that one
![Screenshot_20220202-155142_Lawnchair_1](https://user-images.githubusercontent.com/65810567/152168015-92ff9a03-3ccd-48e0-9a21-c6e4a31b0d7d.png)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
