### ISSUE TITLE
Add Coolapk,Clash,See,WeChat,QQ,Salt Player,and bilibili's icon

### ISSUE THREAD

**Issue by Niswasp** [LawnchairLauncher/lawnicons#32]
App Name:Coolapk
Package Name:com.coolapk.market

App Name:Clash for Android
Package Name:com.github.kr328.clash

App Name:See
Package Name:com.caij.see

App Name:Wechat
Package Name:com.tencent.mm

App Name:QQ
Package Name:com.tencent.mobileqq

App Name:Salt Player
Package Name:com.salt.music

App Name: bilibili
Package Name:tv.danmaku.bili

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
