### ISSUE TITLE
Icon Request: Call of Duty Mobile Garena, SHAREit

### ISSUE THREAD

**Issue by Yurieaijoker** [LawnchairLauncher/lawnicons#322]
Package name
Call of Duty Mobile = "com.garena.game.codm" 
SHAREit = "com.lenovo.anyshare.gps"

**Comment by ZhmieXD** [comment]
CODM is on the way 😉
#297

**Comment by Yurieaijoker** [comment]
Please include the garena version package name. Thank you. 

com.garena.game.codm

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
