### ISSUE TITLE
Icons request (if possible)

### ISSUE THREAD

**Issue by n0setn0bet** [LawnchairLauncher/lawnicons#324]
app:Fotocamera
package:com.google.android.GoogleCamera.Cameight

app:Stocard
package:de.stocard.stocard

app:Immuni
package:it.ministerodellasalute.immuni

app:Imou Life
package:com.mm.android.smartlifeiot

app:Bring!
package:ch.publisheria.bring

app:VerificaC19
package:it.ministerodellasalute.verificaC19

app:Wallet
package:com.droid4you.application.wallet

app:VPN Client Pro
package:it.colucciweb.vpnclientpro

app:Mi Fit
package:com.xiaomi.hm.health

app:DoveConviene
package:it.doveconviene.android

app:AI Life
package:com.huawei.smarthome

Thanks, if possible obv :)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
