### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by Pokorny72** [LawnchairLauncher/lawnicons#327]
Google cloud console: com.google.android.apps.cloudconsole
League of Legends Wild Rift: com.riotgames.league.wildrift
Geekbenchmark:
com.primatelabs.geekbench5
Wulkanowy edziennik:
io.github.wulkanowy
Gcam:
com.GoogleCamera.Burial16

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
