### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/lawnicons#33]
### User Apps

**Aurora Store**
com.aurora.store

~~Bromite~~
~~org.bromite.bromite~~

~~Catogram~~
~~ua.itaysonlab.messenger~~

**NewPipe**
org.schabi.newpipe

**ProtonMail**
ch.protonmail.android

**Bitwarden**
com.x8bit.bitwarden

### System Apps (*ColorOS*)

**OPPO Camera** (*link GCam to OPPO Camera*)
com.oppo.camera

**File Manager** (*link AOSP Files to ColorOS File Manager*)
com.coloros.files

**Photos** (*link Gallery to Photos*)
com.oppo.gallery3d

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
