### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by amogus07** [LawnchairLauncher/lawnicons#336]
Catogram X: 
org.nift4.catox
(Currently linked with old icon from catogram)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
