### ISSUE TITLE
Nekogram themed icon support

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#34]
App name: Nekogram
Package name: tw.nekomimi.nekogram

**Comment by arun54321** [comment]
[nekogram ](https://github.com/LawnchairLauncher/lawnicons/pull/186) It is working now

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
