### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by MdSadam** [LawnchairLauncher/lawnicons#342]
BGMI (pubg) : https://play.google.com/store/apps/details?id=com.pubg.imobile
PhonePe : https://play.google.com/store/apps/details?id=com.phonepe.app
Download Navi - Download Manager : https://play.google.com/store/apps/details?id=com.tachibana.downloader
zArchiver : https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver
gcams : com.google.android.GoogleCamerb , com.GoogleCamera.Burial31, com.GoogleCamera.Burial10 , com.agc.cam

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
