### ISSUE TITLE
Request Icon

### ISSUE THREAD

**Issue by razoration** [LawnchairLauncher/lawnicons#344]
Mobile Legends: Bang Bang
App package : com.mobile.legend

Honkai Impact 3
App package : com.miHoYo.bh3oversea

1.1.1.1
App package : com.cloudflare.onedotonedotonedotone

HoYoLAB
App package : com.mihoyo.hoyolab

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
