### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by adamkhldanial** [LawnchairLauncher/lawnicons#346]
1. MAE (com.maybank2u.life)
2. AfterShip (com.aftership.AfterShip)
3. Airbnb (com.airbnb.android)
4. Air Selangor (com.airselangor.cris.mobile)
5. Bank Islam (com.iexceed.CBS)
6. BigPay (com.tpaay.bigpay)
7. Bundled Notes (com.xaviertobin.noted)
8. Flamingo for Twitter (com.samruston.twitter)
9. Gigi Coffee (com.nexstream.gigiCoffee)
10. Grab (com.grabtaxi.passenger)
11. Huda (com.hudaapp.android)
12. Infinity for Reddit (ml.docilealligator.infinityforreddit) 
13. McDelivery Malaysia (my.com.mcdonalds.delivery) 
14. McDonald's (com.mcdonalds.mobileapp)
15. MySejahtera (my.gov.onegovappstore.mysejahtera)
16. Notion (notion.id)
17. Taskito (com.fenchtose.reflog)
18. TickTick (com.ticktick.task)
19. TnG eWallet (my.com.tngdigital.ewallet)
20. Todoist (com.todoist)
21. Tunetalk (com.tunetalk.jmango.tunetalkimsi)
22. Wahed Invest (com.wahed.mobile)
23. ZUS Coffee (com.coffee.love_coffee) 

Thank you! :)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
