### ISSUE TITLE
Battlegrounds mobile india also known as pubg mobile

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#35]
Battlegrounds mobile india (BGMI) OR PUBG mobile both are same. BGMI is for india and PUBG for global.

App name: Battlegrounds mobile india
Package name: com.pubg.imobile

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
