### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by RudiSalam27** [LawnchairLauncher/lawnicons#354]
Kiwi Browser (com.kiwibrowser.browser)
Retro Music (code.name.monkey.retromusic)
Zoom (us.zoom.videomeetings)
Timestamp Camera (com.jeyluta.timestampcamera)
Sheets (com.google.android.apps.docs.editors.sheets)
Shopee (com.shopee.id)
Tokopedia (com.tokopedia.tkpd)
Mitra Tokopedia (com.tokopedia.kelontongapp)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
