### ISSUE TITLE
Icon request: USB Audio Player Pro

### ISSUE THREAD

**Issue by daemonspudguy** [LawnchairLauncher/lawnicons#359]
If you haven't heard of this app, it's an audiophile grade music player on Android.

**Comment by daemonspudguy** [comment]
Package name : com.extreamsd.usbaudioplayerpro

**Comment by daemonspudguy** [comment]
Please respond.

**Comment by daemonspudguy** [comment]
@patrykmichalik @paphonb  it's been months, and no response. Can I at least have an acknowledgement?

**Comment by RikKoedoot** [comment]
You don't have to be acknowledged, they have seen it but  they don't have to reply to everyone

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
