### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by PriNcEFuL** [LawnchairLauncher/lawnicons#367]
Fastpay(com.sslwireless.fastpay)
Lmc gcam(com.android.hasli.lmc82r7) 
Raid shadow legends(com.plarium.raidlegends) 
Google classroom(com.google.android.apps.classroom) 
ADM(com.dv.adm) 
Snaptube(com.snaptube.premium) 
Viber(com.viber.voip) 
Duolingo(com.duolingo) 
Shareit(com.lenovo.anyshare.gps)

**Comment by Daosdt** [comment]
Greatday (com.dataon.sunfishgo)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
