### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by MastHafe** [LawnchairLauncher/lawnicons#369]
The following icons are not changed when I toggle on "themed icons - Beta"

Google Calendar
Package com.google.android.calendar

awallet
Package org.awallet.cloud

FX Explorer
Package nextapp.fx

BoxToGo
Package de.almisoft.boxtogofull

Google Camera Go
com.google.android.apps.cameralite

**Comment by MastHafe** [comment]
Another one is:
Google Camera Go
com.google.android.apps.cameralite

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
