### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by gaimiPR** [LawnchairLauncher/lawnicons#382]
Intesa Sanpaolo Mobile
com.latuabancaperandroid

Elios APP
it.csystem.android.pess.elios

MyInfoCert
it.infocert.myinfocert.phoenix

N26 - The Mobile Bank
de.number26.android

Curve Card
com.imaginecurve.curve.prd

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
