### ISSUE TITLE
Icon request - codm

### ISSUE THREAD

**Issue by ravencodm** [LawnchairLauncher/lawnicons#384]
Dear developers, please add Call of duty mobile icon 
Package com.activision.callofduty.shooter
![Screenshot_20220213-090633_Lawnchair.png](https://user-images.githubusercontent.com/99584450/153744583-4fe0b56c-3039-46a8-8bfd-d2211fc20691.png)

**Comment by ZhmieXD** [comment]
It's in progress in #297 👍

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
