### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by cMonedula** [LawnchairLauncher/lawnicons#395]
i yearn for minimalism. please and thank you in advance, i'll try to contribute some vectors later as well

Atomas (com.sirnic.atomas)
Equilab (horse.schvung.equilab)
eReader Prestigio (com.prestigio.ereader)
GreenPass (sk.it.greenpass)
Heatos (com.sirnic.heatos)
Huawei Clock (com.android.deskclock)*
Huawei Music (com.android.mediacenter)*
Google Jamboard (com.google.android.apps.jam)
Huawei Calendar (com.android.calendar)*
Huawei Compass (com.huawei.compass)
Microsoft Lens (com.microsoft.office.officelens)
Minesweeper Go (com.EvolveGames.MinesweeperGo)
Odyssey (com.noodlecake.altosodyssey)
Microsoft OneNote (com.microsoft.office.onenote)
Huawei System Manager (com.huawei.systemmanager)
Roll20 (net.roll20.player)
Shadow of Death 2 (com.Bravestars.Stickman.FightingGames.ShadowOfDeath2)
Sketch (com.sonymobile.sketch)
Squire's Dice (com.AaronVanderpoel.SquiresDice)
Steam (com.valvesoftware.android.steam.community)
Ubian (eu.ubian)
Windscribe (com.windscribe.vpn)
Huawei Health (com.huawei.health)

* see #380 for related problem

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
