### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by drishal** [LawnchairLauncher/lawnicons#400]
Can you please add Icon requests for: 
 

- com.crdroid.music 
- com.looker.droidify
- com.xBrowserSync.android
- com.wrx.wazirx
- in.org.npci.upiapp  (BhimUPI)
- com.mobikwik_new
- com.drsants.eggproject (Project Themer)
- com.franko.kernel
- scd.lcex (Logcat Extreme)
- com.vanced.Manager
- com.simplemobiletools.*   [simplemobiletools suite, i.e https://www.simplemobiletools.com )

**Comment by drishal** [comment]
Some more: 
-  com.aurora.services
- microg app

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
