### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by sunaxl13** [LawnchairLauncher/lawnicons#422]
Icon Request For com.avast.android.mobilesecurity or advast mobile security
![55c291ccaf57c178fbfe0d4a2a618fe1111c7b7293e40e577154a075a3b94e3a_200](https://user-images.githubusercontent.com/97773166/156976226-fe2ba03d-8152-4eb8-ad44-851aa68328d6.jpeg)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
