### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by XXDRD** [LawnchairLauncher/lawnicons#423]
Iceraven - io.github.forkmaintainers.iceraven
Newpipe - org.polymorphicshade.newpipe
Mpv - is.xyz.mpv
Blackhole - com.shadow.blackhole
Droid-ify - com.looker.droidify
Feeder - com.nononsenseapps.feeder
Calander - com.android.calendar
Aniyomi - xyz.jmir.tachiyomi.mi
Habits - org.isoron.uhabits
Infinity - ml.docilealligator.infinityforreddit
Jellyfin - org.jellyfin.mobile
Lawnicons - app.lawnchair.lawnicons
Libretorrent - org.proninyaroslav.libretorrent
App manager - io.github.muntashirakon.AppManager
Metro - io.github.muntashirakon.Music
Syncthing-fork - com.github.catfriend1.syncthingandroid
Obsidian - md.obsidian
Owlgram - it.owlgram.android
![IMG_20220307_174343](https://user-images.githubusercontent.com/88576601/157033468-1d7cc453-9e36-4554-ad29-eb94c3fd5e7e.jpg)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
