### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by alexchiu100014** [LawnchairLauncher/lawnicons#432]
I want to request this app

https://play.google.com/store/apps/details?id=tw.com.gamer.android.animad&hl=en_US&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3D%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%E5%8B%95%E7%95%AB%E7%98%8B&pcampaignid=APPU_1_elE7YpqAIIGRr7wPk-qD6Ac

**Comment by alexchiu100014** [comment]
![Screenshot_2022-03-24-00-59-52-83_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/48598830/159755077-a736787c-a735-4840-9c8f-526ca9a1d7c2.jpg)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
