### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by XPaimoNX** [LawnchairLauncher/lawnicons#433]
Call Of Duty: Mobile
app:Call of Duty
package:com.garena.game.codm
Launcher:com.tencent.tmgp.cod.CODMPrivatePermissionActivity

Lazada
app:Lazada
package:com.lazada.android
Launcher:com.lazada.activities.EnterActivity

Ram Cleanup
app:RAM Cleanup
package:com.kosajun.easymemorycleaner
Launcher:com.kosajun.easymemorycleaner.MainActivity

DITO
app:DITO
package:com.mydito
Launcher:com.mydito.ui.login.GuidePageActivity

Sd Maid
app:SD Maid
package:eu.thedarken.sdm
Launcher:eu.thedarken.sdm.main.ui.SDMMainActivity

ForceLTE
app:ForceLTE
package:com.xsquarestudio.forcelte
Launcher:com.xsquarestudio.forcelte.MainActivity

Garena
app:Garena
package:com.garena.gaslite
Launcher:com.garena.gxx.splash.GGSplashActivity

Easy Cache Wiper
app:Easy Cache Wiper
package:com.chornerman.easycachewiper
Launcher:com.chornerman.easycachewiper.MainActivity

GSMArena
app:GSMArena
package:com.gsmarena.android
Launcher:com.gsmarena.android.activity.SplashActivity

LSPosed
app:LSPosed
package:org.lsposed.manager
Launcher:org.lsposed.manager.ui.activity.MainActivity

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
