### ISSUE TITLE
Coloros sytem apps and few other apps icon request

### ISSUE THREAD

**Issue by OkMohit** [LawnchairLauncher/lawnicons#467]
Calculator : com.coloros.calculator

Clock :- com.coloros.alarmclock

Weather :- package:com.coloros.weather2

Photos :- package:com.coloros.gallery3d

Music :- com.oppo.music

Recorder :- com.coloros.soundrecorder

Video :- com.coloros.video

QKSMS :- com.moez.QKSMS

Google Opinion Reward :- com.google.android.apps.paidtasks

Ruthless Launcher :- shubh.ruthless

Cricbuzz :- com.cricbuzz.android

CamScanner :- com.intsig.camscanner

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
