### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by kumarmba** [LawnchairLauncher/lawnicons#472]
1. Zalo
com.zing.zalo

2. PC-Covid
com.mic.bluezone

3. BIDV SmartBanking
com.vnpay.bidv

4. Duolingo
com.duolingo

5. Toss
im.toss.dream

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
