### ISSUE TITLE
Icon Requst

### ISSUE THREAD

**Issue by Creation2283** [LawnchairLauncher/lawnicons#476]
I have some Icon Requests:-
Here are the package names of the apps

From Play Store:-
1. SD Maid - eu.thedarken.sdm
2. Pydroid 3 - ru.iiec.pydroid3
3. Photoshop Express - com.adobe.psmobile
4. Nomad - com.stephaneginier.nomad
5. Mimo - com.getmimo
6. Stumble guys - com.kitikagames.fallbuddies
7. Spaceflight Simulator - com.StefMorojna.SpaceflightSimulator
8. Quick Edit - com.rhmsoft.edit
9. VN Video Editor - com.frontrow.vlog
10. Activity Launcher - de.szalkowski.activitylauncher

Others:-
1. Xiaomi Screen Recorder - com.miui.screenrecorder
2. Xiaomi Game Turbo - com.xiaomi.gameboosterglobal
3. Xiaomi Security - com.miui.securitycenter
4. Xiaomi Weather - com.miui.weather2
5. Xiaomi Recorder - com.android.soundrecorder
6. O Relax(OPPO) - com.coloros.relax
![IMG_20220522_021237](https://user-images.githubusercontent.com/87919051/169669019-e93916d9-fc6f-424e-ba59-3355fbede9bc.jpg)

**Comment by Creation2283** [comment]
I also have attached the image of all the icons

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
