### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Chirag5673** [LawnchairLauncher/lawnicons#480]
BlackHole- com.shadow.blackhole
1dm- idm.internet.download.manager
Apex Legends- com.ea.gp.apexlegendsmobilefps
Calculator- com.coloros.calculator
Phone- com.android.incallui
GameSpace- com.coloros.gamespaceui
Photos- com.coloros.gallery3d
Novau- com.teslacoilsw.launcher
ZArchiver- ru.zdevs.zarchiver
Stumble Guys- com.kitkagames.fallbuddies
Earn to die 2- com.notdroppler.earntodie 2
Mortal Kombat- com.wb.goog.mkx
SD Maid- eu.thedarken.sdm
Freshwalls- com.techburner.freshwalls
Music- com.heytap.music
Home Workout- homeworkout.homeworkouts.noequipment
Nothingbutwalls- com.dev.nothingbutwalls.app
Clock- com.coloros.alarmclock
CloudStream- com.largsdost.cloudstream
File Manager- com.coloros.filemanger
JioTV- com.jio.jioplay.tv
Pikashow- com.offshore.pikachu
Lawnicons- app.lawnchair.lawnicons

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
