### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by unOmni** [LawnchairLauncher/lawnicons#485]
![Screenshot_20220525-211411_Lawnchair.png](https://user-images.githubusercontent.com/106206117/170360063-cfcd542d-8e4d-4b47-b642-6ba9d1a24f66.png)

com.shadow.blackhole
com.samsung.android.calendar
com.sec.android.app.clockpackage
io.legado.app.release
com.samsung.android.contacts
com.sec.android.app.samsungapps
ml.docilealligator.infinityforreddit
org.proninyaroslav.libretorrent
it.owlgram.android

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
