### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by rettetdemdativ** [LawnchairLauncher/lawnicons#486]
Proton Calendar
![1653581917_grim](https://user-images.githubusercontent.com/5265630/170530128-1bf33a34-3fcf-4150-9db7-d48b314d1882.png)
me.proton.android.calendar

Overdrop
![1653581843_grim](https://user-images.githubusercontent.com/5265630/170529955-cd3742df-0877-4080-9d55-dfd192f713a1.png)
widget.dd.com.overdrop.free

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
