### ISSUE TITLE
Ability to add icons for PWAs

### ISSUE THREAD

**Issue by ThatOneCalculator** [LawnchairLauncher/lawnicons#505]
I'm not even sure if this is possible, but if there's a way that icons could be made for PWAs, that would be amazing.

**Comment by SuperDragonXD** [comment]
If I remember correctly, I think it's just possible to manually link the correct icon (see CONTRIBUTING.md) to the package name of the web app. So it's definitely possible.

A package name is needed though.

**Comment by x9136** [comment]
You can do this in the following form:
```
<item component="ComponentInfo{PWA}" drawable="DRAWABLE" name="APPNAME"/>
```
For example:
![Screenshot 2024-09-14 at 23 01 38](https://github.com/user-attachments/assets/85c70c6e-7808-4ed9-a932-57bb8b4ea698)

It is better to add an PWA without activity, because it is generated. This also means that you can only customize an PWA icon manually. For example, you can do this in the latest Lawnchair.
