### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Cyanic76** [LawnchairLauncher/lawnicons#548]
Hello,

This is an icon request for the following apps:

- Nextcloud Deck - it.niedermann.nextcloud.deck
- OpenTracks - de.dennisguse.opentracks
- Gadgetbridge - nodomain.freeyourgadget.gadgetbridge
- Etar - org.lineageos.etar
- FX - nextapp.fx

There are other apps I have installed but icon requests for those already exist.

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
