### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by PMorkab** [LawnchairLauncher/lawnicons#558]
Yandex.Music - ru.yandex.music
Yandex.Maps - ru.yandex.yandexmaps
 Mir Pay - run.nspk.mirpay
Альфа-Банк -  ru.alfabank.mobile.android
Сбербанк -  ru.sberbankmobile
Tinkoff - com.idamob.tinkoff.android
Tinkoff Investigations - ru.tinkoff.investing

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
