### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by sakib-with-a-h** [LawnchairLauncher/lawnicons#570]
alight motion|com.alightcreative.motion
angry birds 2|com.rovio.baba
audio recorder|com.dimowner.audiorecorder
bkash|com.bKash.customerapp
button mapper|flar2.homebutton
calculator++|org.solovyev.android.calculator
capcut|com.lemon.lvoverseas
clima|co.prestosole.clima
facebook|com.facebook.katpro
find my device|de.nulide.findmydevice
geometry dash|com.robtopx.geometryjumplite
greenify|com.oasisfeng.greenify
just player|com.brouken.player
kde connect|org.kde.kdeconnect_tp
node video|com.shallwaystudio.nodevideo
powertube|ussr.razar.youtube_dl
protonvpn|ch.protonvpn.android
reev pro|com.reevpro.grabsterstudios
rocket|com.dbbl.mbs.apps.main
sav pdf viewer|com.saverio.pdfviewer
savefrom helper|com.example.savefromNex
shadow fight 2|com.nekki.shadowfight
super retro mega wars|com.serwylo.retrowars
tether|com.tplink.tether
twidere x|com.twidere.twiderex
ungoogled chromium|org.ungoogled.chromium.stable

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
