### ISSUE TITLE
Icon Request 

### ISSUE THREAD

**Issue by Hiscusaa** [LawnchairLauncher/lawnicons#571]
i want to request some icon 

![Screenshot_20220618-073252_Lawnchair](https://user-images.githubusercontent.com/107515185/174415249-b01a0287-a74a-4ffb-ae18-e1d08087f5ea.png)
Call of Duty Mobile  -  com.garena.game.codm
Gl tools -  com.superpaninbros.glng
Toram Online - com.asobimo.toramonline

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
