### ISSUE TITLE
More icons please

### ISSUE THREAD

**Issue by marcg87** [LawnchairLauncher/lawnicons#59]
com.coloros.gamespaceui
com.coloros.gallery3d
tv.twitchmod.android.app
com.simplemobiletools.gallery.pro

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
