### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by R715B** [LawnchairLauncher/lawnicons#595]
AntennaPod
de.danoeh.antennapod

AudioAnchor
com.prangesoftwaresolutions.audioanchor

Cryptomator
org.cryptomator

FlorisBoard
dev.patrickgold.florisboard

Geometric Weather
wangdaye.com.geometricweather

Librera PRO
com.foobnix.pro.pdf.reader

Mullvad VPN
net.mullvad.mullvadvpn

Music Player
package:com.simplemobiletools.musicplayer

Noice
com.github.ashutoshgngwr.noice

Notes
com.simplemobiletools.notes.pro

Proton Calendar
me.proton.android.calendar

Shark Clean
com.sharkninja.shark

Standard Notes
com.standardnotes

Tangerine
ca.tangerine.clients.banking.app

Tasks
org.tasks

Voila
com.voila.mobile.android

Weather Network
com.pelmorex.WeatherEyeAndroid

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
