### ISSUE TITLE
Icon Request - YouTube Revanced 

### ISSUE THREAD

**Issue by Enderxity** [LawnchairLauncher/lawnicons#597]
![Screenshot_2022-06-30-15-12-19-83](https://user-images.githubusercontent.com/105967767/176620661-b6b449ab-368b-45b6-8adf-85136e087997.jpg)
app.revanced.android.youtube

Left is yt Vanced and right Is yt Revanced

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.

**Comment by Seandylan123** [comment]
The left one kind of looks cool to be honest i mean it's better than the one we have now
