### ISSUE TITLE
Link the Google FIles icon to Material Files

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/lawnicons#61]
Link the Google Files icon to Material FIles please.
me.zhanghai.android.files
![photo_2021-11-12_17-10-54](https://user-images.githubusercontent.com/85034961/141472385-9869b5c6-436c-4822-b4fb-c5f72dfc0c46.jpg)

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
