### ISSUE TITLE
App Request for Lawnicons

### ISSUE THREAD

**Issue by Blank-Slate7** [LawnchairLauncher/lawnicons#615]
[icon_request_22_07_2022_11_41_11.zip](https://github.com/LawnchairLauncher/lawnicons/files/9164439/icon_request_22_07_2022_11_41_11.zip)

yo wassup lawnchair team im loving your new lawnicons dev version with 400 apps and I find these 9 icons to not support the icons here's the info I extracted :]

sending my support to yall

**Comment by SuperDragonXD** [comment]
As said in [README.md](https://github.com/LawnchairLauncher/lawnicons#requesting-icons), icon requests go to https://forms.gle/Fx8vZAiWdW1Tyjo57. Please use the form instead of creating an issue related to your icon request. Thanks!

As a side note, `com.aurora.store`, `me.zhanghai.android.files`, `io.github.muntashirakon.Music`, and `dev.kdrag0n.dyntheme` (4/9 apps are done) already exists in the later development versions. Try updating the dev apk to see those icons themed.

> actually why doesnt the lawnicons icon support lawnicon icons

Unsure why they didn't make one.
