### ISSUE TITLE
Icon request about link icon

### ISSUE THREAD

**Issue by Weupoq** [LawnchairLauncher/lawnicons#617]
**package names:**
com.simplemobiletools.calculator
com.simplemobiletools.camera
com.simplemobiletools.contacts.pro
com.simplemobiletools.dialer
com.simplemobiletools.filemanager.pro
com.simplemobiletools.smsmessenger

**Comment by Weupoq** [comment]
and com.simplemobiletools.voicerecorder

**Comment by SuperDragonXD** [comment]
As said in [README.md](https://github.com/LawnchairLauncher/lawnicons#requesting-icons), icon requests go to https://forms.gle/Fx8vZAiWdW1Tyjo57. Please use the form instead of creating an issue related to your icon request. Thanks!

As a side note, `com.simplemobiletools.filemanager.pro` and `com.simplemobiletools.contacts.pro` already exists in the development versions.

**Comment by Weupoq** [comment]
> As said in [README.md](https://github.com/LawnchairLauncher/lawnicons#requesting-icons), icon requests go to https://forms.gle/Fx8vZAiWdW1Tyjo57. Please use the form instead of creating an issue related to your icon request. Thanks!
> 
> As a side note, `com.simplemobiletools.filemanager.pro` and `com.simplemobiletools.contacts.pro` already exists in the development versions.

Sorry, I've learned about the new submission method before this, but since I tried many times and couldn't open the link, I had to submit it this way
