### ISSUE TITLE
Some more icons

### ISSUE THREAD

**Issue by islekcaganmert** [LawnchairLauncher/lawnicons#619]
1- tr.hereus.app
![Screenshot_20220726-193049_Lawnchair](https://user-images.githubusercontent.com/107067529/181060781-86da4644-b7d3-4ce3-b099-2993df96021d.jpg)
2- com.bkmobil.metodbox
![Screenshot_20220726-193312_Lawnchair](https://user-images.githubusercontent.com/107067529/181061255-43ee6f9e-5546-4ec7-b60c-6b709b351bbf.jpg)
3- daldev.android.gradehelper
![Screenshot_20220726-193444_Lawnchair](https://user-images.githubusercontent.com/107067529/181061539-6f494fb3-d235-4555-9036-6adbf4a46fc3.jpg)

Notes:
First app is in early times but it can get installed from third party store and the app will have english in a month
Second app is used by students, teachers, school administrators and parents of member students of all K12 schools;  It is an education platform.
Third app is helper app for students and have 10M+ users (as Play Store says)

**Comment by SuperDragonXD** [comment]
Late reply, but as said in [README.md](/LawnchairLauncher/lawnicons#requesting-icons), icon requests go to https://forms.gle/Fx8vZAiWdW1Tyjo57. Please use the form instead of creating an issue related to your icon request. Thanks!

As a side note, `daldev.android.gradehelper` already exists in the development versions.

**Comment by islekcaganmert** [comment]
I requested from forms but one app that requested is not in Play Store. It can br installed from http://hereus.pythonanywhere.com/download/
