### ISSUE TITLE
Add some icons

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/lawnicons#63]
Add icons for VLC media player, JuiceSSH, F-Droid, Split APK Installer, APK Mirror Installer,  Element, Shazam, Tor Browser and Google GO please.
org.videolan.vlc
com.sonelli.juicessh
org.fdroid.fdroid
com.aefyr.sai
im.vector.app
com.apkmirror.helper.prod
com.shazam.android
org.torproject.torbrowser
com.google.android.apps.searchlite

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
