### ISSUE TITLE
[DISCUSSION] Problem with contributing

### ISSUE THREAD

**Issue by Nido-nid** [LawnchairLauncher/lawnicons#728]
### About this discussion

I tried to contribute some icons to lawnicons. When i finished the pull request i wanted to push it, but i got this error in android studio:
`Can't create a new pull request: Push failed: remote: Permission to LawnchairLauncher/lawnicons.git denied to Nido-nid. unable to access 'https://github.com/LawnchairLauncher/lawnicons.git/': The requested URL returned error: 403`
How do i get permission to submit some icons?

**Comment by SuperDragonXD** [comment]
Thanks for your interest in contributing! If I understand correctly, you're trying to push your fork to this repo and you don't have write access. You should instead push to your fork (https://github.com/Nido-nid/lawnicons), and create a PR in there. Hope it helps! (Note that for general git help, I'd recommend searching Google or Stackoverflow instead of creating an issue.)
