### ISSUE TITLE
More basic icons for wallpaper based theming on homescreen

### ISSUE THREAD

**Issue by MrRobot0707** [LawnchairLauncher/lawnicons#75]
1. Miui Clock (com.android.deskclock)
2. Miui Calender (com.xiaomi.calendar)
3. Miui Camera (com.android.camera)
4. Bromite (org.bromite.bromite)
5. Call of duty (com.activision.callofduty.shooter)
6. Instagram (com.instagram.android)
7. Netflix (com.netflix.mediaclient)
8. Prime video (com.amazon.avod.thirdpartyclient)
9. Poweramp (com.maxmpz.audioplayer)
10. Whatsapp (com.whatsapp)

**Comment by ninopiamonte** [comment]
Already themed: Instagram, netflix, poweramp, whatsapp

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
