### ISSUE TITLE
Pls read this

### ISSUE THREAD

**Issue by Mario110YT** [LawnchairLauncher/lawnicons#779]
### About this discussion

Hey! Can somone make Lawnicons (same as Launchair 12) avaible on lower version of android like android 7?
Thanks

**Comment by SuperDragonXD** [comment]
Hey there! We don't really support lower versions of Android because of the following reasons:
* Google no longer supports Android versions below 8.1, so why should we?
* It'll be *very* hard and time-consuming to add compatibility support, slowing development even more.
* This will only be used by very few people, even smaller than QuickSwitch users.

Therefore, we don't support these versions and not make apk files for them. Closing this issue.

(Btw, I'd recommend updating/upgrading your device if possible.)
