### ISSUE TITLE
Add some icons

### ISSUE THREAD

**Issue by lilyoo226** [LawnchairLauncher/lawnicons#78]
app:ADM
package:com.dv.adm
Launcher:com.dv.get.Main
app:Calculator
package:com.transsion.calculator
Launcher:com.transsion.calculator.Calculator
app:BlockerX
package:io.funswitch.blocker
Launcher:io.funswitch.blocker.activities.SplashScreenActivity
app:Clock
package:com.transsion.deskclock
Launcher:com.transsion.deskclock.DeskClock

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
