### ISSUE TITLE
How do u find the stuff u have to enter on the sugesstion form

### ISSUE THREAD

**Issue by kittenvr** [LawnchairLauncher/lawnicons#795]
### About this discussion

https://forms.gle/Fx8vZAiWdW1Tyjo57

**Comment by SuperDragonXD** [comment]
Please read the [README.md](https://github.com/LawnchairLauncher/lawnicons/blob/develop/README.md) file:

> If you want to see the requested icons (for contributing purposes), you can view the form responses in our 
[publicly available Google Sheets](https://docs.google.com/spreadsheets/d/1h3eiJnG2nEdR1DbvemaF1lYthHkzYbXvVFPP0TEEt5k/edit?usp=sharing) file.
Note that we currently don't show whether an icon request has been completed or not.

If you meant something else, feel free to further explain what you meant. Otherwise I'll close this issue.
