### ISSUE TITLE
Add 4PDA icon

### ISSUE THREAD

**Issue by incycledream** [LawnchairLauncher/lawnicons#80]
app name: 4PDA
pkg name: ru.fourpda.client

**Comment by TheGreySquare** [comment]
Also this package name for the same icon (it's an unofficial client being used by a lot of folks):

ru.forpdateam.forpda

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
