### ISSUE TITLE
Substratum Lite, Amazon Shopping, eBay, XDA app, Tapatalk Pro and The Athletic app icons please 

### ISSUE THREAD

**Issue by reechings** [LawnchairLauncher/lawnicons#82]

**Comment by reechings** [comment]
projekt.substratum.lite
com.amazon.mShop.android.shopping
com.ebay.mobile
com.xda.labs.play
com.quoord.tapatalkHD
com.theathletic

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
