### ISSUE TITLE
Icon request + link GBWhatsApp

### ISSUE THREAD

**Issue by BlueSlimee** [LawnchairLauncher/lawnicons#86]
Howdy! I'd like to suggest a few icons. I already pushed their SVG files to [my fork](https://github.com/blueslimee/lawnicons), however they aren't following the icon guidelines (4x4 spacing) nor have they been converted to XML.
- Authy (`com.authy.authy`)
- Wavelet (`com.pittvandewitt.wavelet`)
- ProtonMail (`ch.protonmail.android`)
- G1 (`com.globo.g1.app`)
- Globoplay (`com.globo.globotv`)

Also, linking GBWhatsApp (a WhatsApp mod) to the WhatsApp drawable would be very nice.
Thanks!

**Comment by lawnchairci** [comment]
Hello! Weʼre switching to a new system for icon requests in order to be able to better manage them. From now on, icon requests can be submitted here: https://forms.gle/Fx8vZAiWdW1Tyjo57. If your icon request hasnʼt yet been fulfiled, it has been copied to our new icon request database, meaning no action is required. Consequently, this issue will be closed.
