### ISSUE TITLE
Etar not linking to calendar icon

### ISSUE THREAD

**Issue by Sir-Photch** [LawnchairLauncher/lawnicons#989]
### About this discussion

Even though the entry for `ws.xsoh.etar` exists, the calendar icon is not applied. This happens on the most recent debug-build.

**Comment by naveenccmsd** [comment]
![WhatsApp Image 2023-01-27 at 2 41 51 AM](https://user-images.githubusercontent.com/7315975/214951506-f42ea74c-f274-4241-b349-f3a5579d8ef1.jpeg)
The play store version is working for me , can you share the app component name for the apk you installed?

you can follow below guid to get it.
https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#using-3rd-party-apps

**Comment by Sir-Photch** [comment]
```
ws.xsoh.etar
com.android.calendar.AllInOneActivity
```

IIRC this is correct in the .xml

**Comment by naveenccmsd** [comment]
Can you share the lawnicons version , lawnchir version. I have tried with recent builds with both alph 4 and alpha 5 version of lawnchir,Even in other thirdparty launcher (I tested no Nova) it's working fine.

Also try to 

- retstart Lawnchair 
- check `rest to defult`  in customise icon

**Comment by Sir-Photch** [comment]
Dev #1495

Did you test Kvaesitso? That's what I'm using.


Am 28. Januar 2023 11:04:02 MEZ schrieb Naveen ***@***.***>:

**Comment by naveenccmsd** [comment]
I have checked kavaesiso, it's not working. The problem is with kvaestso launcher, it somehow consider lawnicons as themedicon alone and not supporting dynamic calendar icons except Google Calendar.

1.The fix should be from launcher because other launchers, it's working fine, I have tested in lawncher, nova, rootless pixel launcher

2. As a workaround we can add static Calendar icon in lawnicons for the launcher which is not supporting dynamic calendar icons. But I need test if this has any impact with dynamic calendar

**Comment by naveenccmsd** [comment]
@Sir-Photch , with this build https://github.com/LawnchairLauncher/lawnicons/pull/1007 , Etar calendar appiled in Kvaesitso launcher but with static calendar icons . To have it dynamic calendar please raise issuw with Kvaesitso team.

**Comment by daywalk3r666** [comment]
![Screenshot_20230129-104306_Trebuchet](https://user-images.githubusercontent.com/15938117/215318696-2e1274c4-9d0b-4bb5-a171-a4739fe7c5f9.png)

**Comment by Sir-Photch** [comment]
Yep, that build works for me, albeit being fixed to the 31st.
